Portfolio start
MarcoDDM/portfolio pull request #1
Opened 2022-12-03 10:15 UTC by MarcoDDM

For this feature branch I:

-add linters configuration.
-add styles for the mobile version.
-set up the HTML for the headline and the navbar.

2022-12-03 10:55 UTC, iambenkis requested changes
Hi @MarcoDDM , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that needs to satisfy the following requirements:
- [ ] Your ReadMe does not conform to the **new** [standardized ReadMe template](https://github.com/microverseinc/readme-template). Kindly ensure that all the headers from the [README template](https://github.com/microverseinc/readme-template) are  present in your repo, and then request another review

**[New ReadMe Template](https://github.com/microverseinc/readme-template):**
![image](https://user-images.githubusercontent.com/12745474/204060829-8c9841df-03ac-4b69-acb8-c44744bad566.png)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-05 16:20 UTC, tufoinnkuo10 requested changes
Hi @MarcoDDM 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally


Required Changes ♻️
Check the comments under the review
![tufoin](https://media.giphy.com/media/ksPoGhnZvHP4QoYT1m/giphy.gif)

Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-12-05 16:20 UTC, tufoinnkuo10 commented on index.html
> +        <a href="#" class="hamburger"><img src="images/hamburger.svg"/></a>
- [x] great job.  for semantics reason the Hamburger icon should have a `nav `tag

2022-12-05 16:20 UTC, tufoinnkuo10 commented on index.html
> +        <h2>Hello! I am a software developer!
- [ ] kindly put this in a `p `tag
- [ ] please respect the figma font weight, size and line height

2022-12-05 16:20 UTC, tufoinnkuo10 commented on index.html
> +
- [ ] please ensure The container of the section is a `section` tag.

* It represents a generic standalone section of the document, so use it.

2022-12-05 16:20 UTC, tufoinnkuo10 commented on index.html
> +        <button class="collab">Start collaboration</button>
- [ ] kindly add a link placeholder to the button

2022-12-05 16:20 UTC, tufoinnkuo10 commented on index.html
> +
- [ ] great job. Please reduce the gap between the text and start collaboration button like that of Figma.
- [ ] also, you are missing the image under the start collaboration button . please, kindly add that.

yours
![Screenshot (634)_LI](https://user-images.githubusercontent.com/65298048/205687206-ddaf7a7a-dd45-4202-806f-53545e9c3ad1.jpg)
figma
![Screenshot (633)](https://user-images.githubusercontent.com/65298048/205687320-19aa2767-c9ec-4734-87cd-1f9cd129d45e.png)

2022-12-05 19:55 UTC, algerina approved these changes
# STATUS: Approved  🥳   🎉🎉🎉

### Hello @MarcoDDM 
 ✋🏼 Nice done with working on last review. I am impressed. Your project is great. There is nothing else to say other than... it's time to merge it!

### Cheers and Happy coding! 💻 👏
<img src="https://media2.giphy.com/media/l7fdqmHQ1jCg2HzQlx/giphy.gif"/>


HIGHLIGHTS 
- No linter errors
- Descriptive PR and commits
- Your project looks Great!
___
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

2022-12-05 22:16 UTC, merged