Mobile menu
MarcoDDM/portfolio pull request #11
Opened 2023-01-03 18:23 UTC by MarcoDDM

**On this pull request:**

-  Create a new Menu for the mobile version
- When the user clicks (or taps) the hamburger button, the mobile menu appears.
- When the user clicks (or taps) the close (X) button, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, the correct part of the page is displayed.

2023-01-03 23:17 UTC, tufoinnkuo10 requested changes
Hi @TEAM

There are some issues that you still need to work on to go to the next project, but you are almost there!

To Highlight
✅ You used the correct GitHub flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ Mobile popup works as expected


Required Changes ♻️
Check the comments under the review

![tufoin](https://media.giphy.com/media/l46CxmW82zcQiRghG/giphy.gif)

Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-01-03 23:17 UTC, tufoinnkuo10 commented on index.html
> +			<li><a class="mobile-item scroll-link" href="#Form">Contact</a>
- [x] Great work. Please kindly give the menu links black color like in the original design
- [x] kindly ensure that when any of the links are clicked, it takes you to the correct page section. This will ease accessibility of your portfolio. Great job

2023-01-03 23:17 UTC, tufoinnkuo10 commented on index.html
> +		<nav class="burger" onclick="showMobileMenu()"> <a class="hamburger"><img src="images/hamburger.svg" /></a>
- [optional] great work. I suggest you make your whole mobile version responsive instead of just the harmburger icon when the screen size changes. this will make your work look more professional

![Screenshot (700)_LI](https://user-images.githubusercontent.com/65298048/210456124-c1b4fbb4-d59b-4b6f-a22c-a4b30508c305.jpg)

2023-01-03 23:17 UTC, tufoinnkuo10 commented on index.html
> +		</nav>
- [ ] please make the mobile menu responsive as well, until the desktop screen size. this allows your website content to flow freely across all screen resolutions and sizes, and renders it to look great on all devices
![Screenshot (701)_LI](https://user-images.githubusercontent.com/65298048/210456795-ad0aec8e-a058-4ec8-b7dd-5ab140eeeb16.jpg)

2023-01-03 23:17 UTC, tufoinnkuo10 commented on index.html
> +		<!--MOBILE MENU-->
- [ ] please kindly ensure when it is converted to the desktop version, the mobile menu and its items disappear. Kindly fix that. you can set them to `display:none` on the Desktop version
![Screenshot (702)_LI](https://user-images.githubusercontent.com/65298048/210456987-d02cef49-49ed-4bf5-9121-6c181a4ac69d.jpg)

2023-01-04 18:53 UTC, amejid approved these changes
Hi @MarcoDDM, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Correct use of Github flow :heavy_check_mark: 
- Linter checks passing :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-04 18:56 UTC, merged